#make sure roles have defaults for now
#dotfiles_root: "{{ ansible_env.HOME }}/.local/share/dotfiles"

gpg_key: 0CDC76D5C109D17AAA6A71FAD5A34F776D49C905

install_default_packages: yes
install_extra_packages: yes

basic_packages:
  - stow
  - git
  - zsh
  - byobu
  - neovim
  - lsd
  - starship
  - gpg
  - pinentry
  - pass

default_packages:
  - bat
  - fzf
  - fortunes
  - direnv

extra_packages:
  - android
  - ansible
  - starship
