#!/usr/bin/env sh

source .git/hooks/scripts/variables

# If there are whitespace errors, print the offending file names and fail.
git diff-index --check --cached $CURRENT_HEAD --

if [ $? -ne 0 ]; then
  exit 1
fi
