---

- name: Install oh-my-zsh
  include_role:
    name: installer
  vars:
    package: 
      arch: oh-my-zsh
      ubuntu: curl
    name: oh-my-zsh

- include_tasks: manual.yml
  when: ansible_distribution == "Ubuntu"

