---
- name: "Ensure oh-my-zsh is {{ install_state }}"
  include_role:
    name: installer
  vars:
    system:
      package: curl
    dotfiles: oh-my-zsh

- include_tasks: manual.yml
  when: install_state == 'present'
