---
- name: Check for existing oh-my-zsh install
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: install

- name: Install oh-my-zsh from curl script
  command: /usr/bin/sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  register: result
  failed_when: result.rc != 0
  when: not install.stat.exists
