---
- name: Check for existing oh-my-zsh install
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  register: install

- name: Install oh-my-zsh from git
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    version: "{{ oh_my_zsh_version }}"
    depth: 1
  when: install_state == "present" and not install.stat.exists

- name: Uninstall oh-my-zsh
  file:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
    state: absent
  when: install_state == "absent" and install.stat.exists
