---
- name: "Ensure nerdfonts {{ install_state }}"
  block:
    - set_fact:
        font_install_path: "{{ ansible_env.HOME }}/Library/Fonts"
      when: ansible_distribution == "MacOSX"

    - file:
        path: "{{ font_install_path }}"
        state: directory
      when: install_state == "present"

    - file:
        path: "{{ nerdfonts_extract_dir }}"
        state: directory
      when: install_state == "present"

    - name: Download nerd fonts archive
      get_url:
        url: "{{ nerdfonts_release_url }}"
        dest: "/tmp/{{ nerdfonts_release_asset }}"
        mode: "0644"
        checksum: "sha256:{{ nerdfonts_release_sha256 }}"
      when: install_state == "present"

    - name: Extract nerd fonts archive
      unarchive:
        src: "/tmp/{{ nerdfonts_release_asset }}"
        dest: "{{ nerdfonts_extract_dir }}"
        remote_src: true
      when: install_state == "present"

    - name: Install nerd fonts
      copy:
        src: "{{ nerdfonts_extract_dir }}/{{ item.file }}"
        dest: "{{ font_install_path }}/{{ item.file }}"
        mode: "0644"
      with_items: "{{ font_items }}"
      when: install_state == "present"

    - file:
        path: "{{ font_install_path }}/{{ item.file }}"
        state: "{{ install_state }}"
      with_items: "{{ font_items }}"
      when: install_state == "absent"
