
- name: Configure stow
  template:
    src: "stowrc.j2"
    dest: "{{ ansible_env.HOME }}/.stowrc"
  vars:
    target_dir: "{{ ansible_env.HOME }}"

- name: Install stow
  include_role: 
    name: installer
  vars:
    name: stow
