---
- name: Configure system
  include_role:
    name: installer
  vars:
    package: stow
    notify: "configure {{ install_state }}"

- name: Stow self
  include_role:
    name: installer
  vars:
    dotfiles: stow
