
- name: Install stow | role
  include_role: 
    name: installer
  vars:
    system: stow

- name: Ensure stow path exists
  file:
    path: "{{ stow_root }}/stow"
    state: directory

- name: Configure stow | template
  template:
    src: "stowrc.j2"
    dest: "{{ ansible_env.HOME }}/.stowrc"
  vars:
    target_dir: "{{ ansible_env.HOME }}"

- name: Copy files to stow root | copy
  copy:
    src: files/
    dest: "{{ stow_root }}/stow/"

- name: Stow self | role
  include_role:
    name: installer
  vars:
    stow: stow