
- name: Install stow | role
  include_role: 
    name: installer
  vars:
    package: stow

- name: Configure stow | template
  template:
    src: "stowrc.j2"
    dest: "{{ ansible_env.HOME }}/.stowrc"
  vars:
    target_dir: "{{ ansible_env.HOME }}"

- name: Copy files to stow root | copy
  copy:
    src: files/
    dest: "{{ stow_root }}/"

- name: Stow self | role
  include_role:
    name: installer
  vars:
    stow: stow