directory: __DUBNIUM_MUSIC_DIRECTORY__
library: __DUBNIUM_BEETS_LIBRARY__

import:
  move: yes
  write: yes
  copy: no
  resume: yes
  incremental: yes

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: Singles/$artist/$title
  comp: Compilations/$album%aunique{}/$track $title

plugins:
  - fetchart
  - embedart
  - lastgenre
  - duplicates
  - missing
  - info
