---
- name: "Ensure ansible is {{ install_state }}"
  include_role:
    name: installer
  vars:
    name: ansible

- name: Generate vault pass
  command: "pass generate ansible-vault-password"
  when: install_state == "present"
