---
- name: Install bat
  include_role:
    name: installer
  vars:
    name: bat


- name: Update alternatives on ubuntu
  community.general.alternatives:
    name: bat
    path: /usr/bin/batcat
    link: /usr/bin/cat
  become: true
  when: ansible_distribution == 'Ubuntu'
