---
- block:
    - name: Ensure git conf.d directory exists
      file:
        path: "{{ dotfiles_root }}/git/.config/git/conf.d/"
        state: directory
        mode: "0755"

    - name: Configure git user
      template:
        src: templates/user.j2
        dest: "{{ dotfiles_root }}/git/.config/git/conf.d/user"
      when: git_user is defined

    - name: Configure git on mac
      copy:
        src: files/config/mac
        dest: "{{ dotfiles_root }}/git/.config/git/conf.d/mac"
      when: ansible_distribution == "MacOSX"

  when: install_state == 'present'

- name: "Ensure git is {{ install_state }}"
  include_role:
    name: installer
  vars:
    name: git
