---
- name: Install git
  include_role:
    name: installer
  vars:
    name: git

- name: Configure git user
  template:
    src: templates/user.j2
    dest: "{{ dotfiles_root }}/git/.config/git/conf.d/user"
  when: git_user is defined
