---
- name: "Ensure neovim is {{ install_state }}"
  include_role:
    name: installer
  vars:
    name: neovim

- name: "Ensure neovim dependencies are {{ install_state }}"
  include_role:
    name: installer
  vars:
    package: "{{ item }}"
  with_items: "{{ neovim_util_packages }}"

- block:
    - name: Check Neovim Packer directory
      stat:
        path: "{{ neovim_packer_install_dir }}"
      register: packer

    - name: Install Neovim Packer
      command: "git clone --depth 1 https://github.com/wbthomason/packer.nvim {{ neovim_packer_install_dir }}"
      when: not packer.stat.exists

    - name: Synchronize packer packages
      command: "nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'"

  when: install_state == 'present'

- block:
    - name: Uninstall Neovim Packer
      file:
        path: "{{ neovim_packer_install_dir }}"
        state: absent

  when: install_state == 'absent'
