---
- name: "Ensure taskwarrior is {{ install_state }}"
  include_role:
    name: installer
  vars:
    name: task

- name: "Install timewarrior"
  pip:
    name: taskwarrior-time-tracking-hook
    state: "{{ install_state }}"
  when: timewarrior_enabled == true

- block:
    - name: "Install systemd task sleep script"
      copy:
        src: "systemd/system-sleep/{{ task_sleep_script_name }}"
        dest: "{{ systemd_sleep_dir }}/"
      when: systemd_enabled == true

    - name: "Link time tracking hook"
      file:
        state: link
        src: "{{ timewarrior_hook_src }}"
        dest: "{{ task_hooks_dir }}/on-modify.timetracking"
      when: timewarrior_enabled == true

  when: install_state == "present"

- block:
    - name: "Remove systemd sleep script"
      file:
        state: absent
        path: "{{ systemd_sleep_dir }}/{{ task_sleep_script_name }}"
      when: systemd_enabled == true

    - name: "Unlink time tracking hook"
      file:
        state: absent
        src: "{{ task_hooks_dir }}/on-modify.timetracking"
      when: timewarrior_enabled == true

  when: install_state == "absent"
