#!/usr/bin/env sh

function check_submodules() {
  if [ ! -f .gitmodules ]; then
    return 0
  fi

  echo >&2 "Pushing submodules"

  git submodule foreach git push

  return $?
}

if test check_submodules != 0; then
  exit 1
fi
