---
- name: Configure install
  set_fact:
    install_state: present
    install_packages: "{{ basic_packages }}"

- name: Configure default packages
  set_fact:
    install_pakages: "{{ install_packages + default_packages }}"
  when: install_default_packages
  tags:
    - default

- name: Configure extra packages
  set_fact:
    install_pakages: "{{ install_packages + extra_packages }}"
  when: install_extra_packages
  tags:
    - extra

- name: Install packages
  include_role:
    name: "{{ item }}"
    apply:
      tags:
        - "{{ item }}"
        - install
  when:
    - (ansible_run_tags == ['install'] and ansible_skip_tags == []) or (item in ansible_run_tags) or (item not in ansible_skip_tags and (item in ansible_run_tags or ansible_run_tags == ['install']))
  loop: "{{ install_packages }}"
  tags:
    - packages
