---
- name: Setup motd
  copy:
    src: files/motd
    dest: /etc/motd
  become: true
  tags:
    - never
    - install

- name: Remove motd
  file:
    path: /etc/motd
    state: absent
  become: true
  tags:
    - never
    - uninstall
