
# docker-compose.override.yml
services:
  arxiv-mcp:
    deploy:
      replicas: 0
  calculator-mcp:
    deploy:
      replicas: 0
  chatsum-mcp:
    deploy:
      replicas: 0
  context-awesome:
    deploy:
      replicas: 0
  conventional-commits:
    deploy:
      replicas: 0
  docker-mcp:
    deploy:
      replicas: 0
  fetch-mcp:
    deploy:
      replicas: 0
  filesystem:
    deploy:
      replicas: 0
  ghidra-mcp:
    deploy:
      replicas: 0
  gradle-mcp:
    deploy:
      replicas: 0
  hub-mcp:
    deploy:
      replicas: 0
  investor-agent:
    deploy:
      replicas: 0
  kaggle-mcp:
    deploy:
      replicas: 0
  kubectl-mcp:
    deploy:
      replicas: 0
  language-mcp:
    deploy:
      replicas: 0
  local-rag-mcp:
    deploy:
      replicas: 0
  mcp-gateway:
    deploy:
      replicas: 0
  mcp-scan:
    deploy:
      replicas: 0
  mermaid-diagrams:
    deploy:
      replicas: 0
  mobsf-mcp:
    deploy:
      replicas: 0
  opentofu:
    deploy:
      replicas: 0
  pandoc-mcp:
    deploy:
      replicas: 0
  piloty-mcp:
    deploy:
      replicas: 0
  postman-mcp:
    deploy:
      replicas: 0
  semgrep-mcp:
    deploy:
      replicas: 0
  sequential-thinking:
    deploy:
      replicas: 0
  shrimp-task-manager:
    deploy:
      replicas: 0
  src-to-kb:
    deploy:
      replicas: 0
  summarizer-mcp:
    deploy:
      replicas: 0
  sysoperator:
    deploy:
      replicas: 0
  taskwarrior-mcp:
    deploy:
      replicas: 0
  token-optimizer-mcp:
    deploy:
      replicas: 0
  user-feedback-mcp:
    deploy:
      replicas: 0
