---
- name: Install arch user repository
  community.general.pacman:
    name: "{{ arch_package }}"
    update_cache: yes
    state: present
  become: true
  when: ansible_distribution == "Archlinux" and arch_package
