- name: Install arch user repository
  community.general.pacman:
    name: "{{ system.arch | default(system) }}"
    update_cache: yes
    state: present
  become: true
  when: ansible_distribution == "Archlinux"
