---
- name: "Ensure {{ arch_package}} is {{ install_state }} with pacman"
  block:
    - community.general.pacman:
        name: "{{ arch_package }}"
        update_cache: yes
        state: "{{ install_state }}"
      become: true
  rescue:
    - kewlfft.aur.aur:
        name: "{{ arch_package }}"
        update_cache: yes
        state: "{{ install_state }}"
      become: true
