- name: Install arch user repository
  community.general.pacman:
    name: "{{ package }}"
    update_cache: yes
    state: present
  become: true
  when: ansible_distribution == "Archlinux" and package is defined
