---
- block:
    - name: "Create directory for {{ dotfiles_directory }}"
      file:
        path: "{{ dotfiles_root }}/{{ dotfiles_directory }}"
        state: directory

    - name: "Copy dotfiles for {{ dotfiles_directory }}"
      synchronize:
        src: "{{ ansible_parent_role_paths[0] }}/files/dotfiles/"
        dest: "{{ dotfiles_root }}/{{ dotfiles_directory }}/"
        delete: true

  when: install_state == "present"

- name: "Remove dotfiles for {{ dotfiles_directory }}"
  file:
    path: "{{ dotfiles_root }}/{{ dotfiles_directory }}/"
    state: "{{ install_state }}"
  when: install_state == "absent"
