---
- block:
    - name: "Create directory for {{ dotfiles_directory }}"
      file:
        path: "{{ dotfiles_root }}/{{ dotfiles_directory }}"
        state: directory

    - name: "Copy dotfiles for {{ dotfiles_directory }}"
      copy:
        src: "files/dotfiles/"
        dest: "{{ dotfiles_root }}/{{ dotfiles_directory }}/"
        mode: preserve

  when: install_state == "present"

- name: "Remove dotfiles for {{ dotfiles_directory }}"
  file:
    path: "{{ dotfiles_root }}/{{ dotfiles_directory }}/"
    state: "{{ install_state }}"
  when: install_state == "absent"
