---
- name: Run install
  block:
    - name: "Ensure system packages are {{ install_state }}"
      import_tasks: system.yml

    - name: "Ensure files are {{ install_state }}"
      import_tasks: files.yml
  when: install_state == "present"
  tags:
    - never
    - install

- name: Run uninstall
  block:
    - name: "Ensure files are {{ install_state }}"
      import_tasks: files.yml

    - name: "Ensure system packages are {{ install_state }}"
      import_tasks: system.yml
  when: install_state == "absent"
  tags:
    - never
    - uninstall

- name: "Notify handlers of {{ notify }}"
  assert:
    quiet: true
    that: true
  changed_when: notify is not undefined
  when: notify is not undefined
  notify:
    - "{{ notify }}"

- name: Flush handlers
  meta: flush_handlers
  when: notify is not undefined
