---
# tasks file for installer
- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- include_tasks: macos.yml
  when: ansible_distribution == "MacOSX"

- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux"
