
- include_tasks: system.yml
  when: package is defined or packages is defined or name is defined

- include_tasks: dotfiles.yml
  when: dotfiles is defined or name is defined

- include_tasks: stow.yml
  when: stow is defined or name is defined

