---
- include_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu' and ubuntu_package

- include_tasks: macos.yml
  when: ansible_distribution == "MacOSX" and macos_package

- include_tasks: arch.yml
  when: ansible_distribution == "Archlinux" and arch_package
