---
- include_tasks: ubuntu.yml
  vars:
    item: "{{ package.ubuntu | default(package.name) | default(name) | default(omit) }}"
    items: "{{ packages.ubuntu | default(packages) | default(omit) }}"
  when: ansible_distribution == 'Ubuntu'

- include_tasks: macos.yml
  vars:
    item: "{{ package.macos | default(package.name) | default(name) | default(omit) }}"
    items: "{{ packages.macos | default(packages) | default(omit) }}"
  when: ansible_distribution == "MacOSX"

- include_tasks: arch.yml
  vars:
    item: "{{ package.arch | default(package.name) | default(name) | default(omit) }}"
    items: "{{ packages.arch | default(packages) | default(omit) }}"
  when: ansible_distribution == "Archlinux"
