
- debug:
   var: item
- debug:
   var: items

- name: Install ubuntu packages
  apt:
    pkg: "{{ item | default(items) }}"
    update_cache: yes
    state: present
  become: true
  when: item is defined or items is defined


