---

- name: Install zsh
  include_role:
    name: installer
  vars:
    name: zsh

- name: Set zsh as default shell
  become: yes
  become_user: root
  command: chsh -s /bin/zsh {{ ansible_env.USER }}
  register: zsh_for_user
  failed_when: zsh_for_user.rc >= 1
  changed_when: zsh_for_user.rc == 0

- name: Install zsh completions
  include_role:
    name: installer
  vars:
    system:
      macos: zsh-completions
      arch: zsh-completions

- name: Install files
  include_role:
    name: installer
  vars:
    stow: zsh
