---
- name: "Prepare current zsh config"
  include_tasks: setup.yml
  loop:
    - ".zshrc"
    - ".zshenv"
    - ".config/zsh/.zshrc"
  when: install_state == "present"

- name: "Ensure zsh is {{ install_state }}"
  include_role:
    name: installer
  vars:
    name: zsh

- name: Set zsh as default shell
  become: yes
  become_user: root
  command: chsh -s /bin/zsh {{ ansible_env.USER }}
  register: zsh_for_user
  failed_when: zsh_for_user.rc >= 1
  changed_when: zsh_for_user.rc == 0
  when: install_state == 'present'

- name: "Ensure zsh completions are {{ install_state }}"
  include_role:
    name: installer
  vars:
    system:
      macos: zsh-completions
      arch: zsh-completions

- name: "Ensure manjaro specific zsh config"
  copy:
    src: manjaro
    dest: "{{ ansible_env.HOME }}/.config/zsh/.zshrc"
  when: install_state == "present" and ansible_os_family == "Manjaro"

- name: "Ensure zsh config"
  copy:
    src: default
    dest: "{{ ansible_env.HOME }}/.config/zsh/.zshrc"
  when: install_state == "present" and ansible_os_family != "Manjaro"
