name: Local Assistant
version: 1.0.0
schema: v1
context:
  - provider: code
  - provider: docs
  - provider: diff
  - provider: terminal
  - provider: problems
  - provider: folder
  - provider: codebase
models:
  - name: Gemma3 Small 
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: gemma3:270m
  - name: Granite3.2 Vision 
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: granite3.2-vision:2b-q8_0
  - name: Qwen2.5 Vision
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: qwen2.5vl:7b-q8_0
  - name: Granite Embedding
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: granite-embedding:latest
    roles:
      - embed
      - chat
      - edit
      - apply
      - summarize
  - name: Mistral Small
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: mistral-small:24b
  - name: Nemotron Mini
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: nemotron-mini:4b
  - name: Granite3 MoE
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: granite3-moe:1b
  - name: SMoLL2
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: smollm2:360m
  - name: Command-R
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: command-r7b:7b
  - name: DeepSeek-R1
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: deepseek-r1:8b
  - name: Cognito
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: cogito:8b
  - name: Qwen3
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: qwen3:8b-q8_0
  - name: Granite3.3
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: granite3.3:latest
  - name: Qwen2.5 Coder
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: qwen2.5-coder:latest
    roles:
      - autocomplete
      - edit
      - apply
      - summarize
  - name: DeepSeek Coder
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: deepseek-coder-v2:latest
    roles:
      - autocomplete
      - edit
      - apply
      - summarize
  - name: Gemma3n
    provider: ollama 
    apiBase: http://dubnium:11434 
    model: gemma3n:latest
  - name: LocalLLama
    provider: ollama
    apiBase: http://localhost:11434
    model: AUTODETECT
prompts:
  - name: check
    description: Check for mistakes in my code
    prompt: |
      Please read the highlighted code and check for any mistakes. You should look for the following, and be extremely vigilant:
        - Syntax errors
        - Logic errors
        - Security vulnerabilities
  - name: arch
    description: Apply architecture principles
    prompt: | 
      Please read the highlighted code and suggest improvements and refactors for 
      SOLID principles and clean architecture. You should look for the following, and be extremely vigilant:
        - data, domain, presentation, application and ai horizontal layers 
        - SOLID principles
        - dependency injection opportunities
        - testable humble objects
        - layer and data boundaries
        - use cases or vertical layers that combine other components
        - packaging strategies and modularization (features, hexogonal, component)
        - details to abstract
        - minimal changes
        - data mapping
  - name: profile
    description: Evaluate a resume for a job
    prompt: |
      Provide me with a candidate profile score for this resume and this job. 
      Include an overall score and a score for each skill. 
      Include areas where I can improve my resume, and an example of a 
      qualitative and a quantitative resume accomplishment for the skill.
