#!/usr/bin/env sh

source .git/hooks/scripts/functions
source .git/hooks/scripts/variables

h1 "Prevent default branch"

if [ "$CURRENT_BRANCH" = "${DEFAULT_BRANCH}" ]; then
   fail "Direct commits to the default branch are not allowed."
else
  pass "Branch is not default"
fi