---
- name: "Ensure android studio is {{ install_state }}"
  include_role:
    name: installer
  vars:
    package: android-studio

- name: "Ensure android config is {{ install_state }}"
  include_role:
    name: installer
  vars:
    dotfiles: android
