#!/usr/bin/env sh

exec 1>&2

function h1() {
  printf "\n\x1B[1;39m> %s\n" "$@"
}

function pass() {
  printf "\x1B[1;33m✔\x1B[0m %s\n" "$@"
}

function fail() {
  printf "\x1B[1;31m✖\x1B[0m %s\n" "$@"
  exit 1
}

function failsafe() {
  printf "\x1B[1;31m✖\x1B[0m %s\n" "$@"
}

commit_files() {

  if [ $# -eq 0 ] ; then
      echo $(git diff-index --name-only --diff-filter=ACM --cached HEAD --)
      exit 0
  fi

  extensions=''
  for extension in "$@"
  do
    extensions="${extensions}(${extension})|"
  done
  regex="\.(${extensions%?})$"
  echo $(git diff-index --name-only --diff-filter=ACM --cached HEAD -- | grep -P "$regex")
}
