---
- name: "Ensure gpg is {{ install_state }}"
  include_role:
    name: installer
  vars:
    name: gnupg

- block:
    - name: Set permissions
      file:
        path: "{{ ansible_env.HOME }}/.gnupg"
        state: directory
        mode: g-rxw,o-rxw

    - name: Generate config
      template:
        src: gpg.conf.j2
        dest: "{{ ansible_env.HOME }}/.gnupg/gpg.conf"

    - name: Import gpg key
      command: "gpg --keyserver hkps://keyserver.ubuntu.com --receive-keys {{ gpg_key }}"
      when: gpg_key is defined

    - name: Import gpg key
      command: "echo -n '{{ gpg_private_key }}' | gpg --import -"
      when: gpg_private_key is defined

  when: install_state == "present"

- block:
    - name: Remove gpg key
      command: "gpg --delete-keys {{ gpg_key }}"
      when: gpg_key is defined

    - name: Remove gpg key
      command: "gpg --delete-secret-keys {{ gpg_key }}"
      when: gpg_key is defined and gpg_private_key is defined

  when: install_state == "absent"
