---
- block:
    - name: Install starship for ubuntu
      block:
        - name: Download starship release
          get_url:
            url: "{{ starship_release_url }}"
            dest: "/tmp/{{ starship_release_asset }}"
            mode: "0644"
            checksum: "sha256:{{ starship_release_sha256 }}"

        - name: Extract starship binary
          unarchive:
            src: "/tmp/{{ starship_release_asset }}"
            dest: /usr/local/bin
            remote_src: true
          become: true

        - name: Ensure starship is executable
          file:
            path: /usr/local/bin/starship
            mode: "0755"
          become: true
      when: install_state == "present"

    - name: Uninstall starship from ubuntu
      file:
        path: /usr/local/bin/starship
        state: absent
      become: true
      when: install_state == "absent"

  when: ansible_distribution == 'Ubuntu'

- name: "Ensure starship is {{ install_state }}"
  include_role:
    name: installer
  vars:
    system:
      macos: starship
      arch: starship
    dotfiles: starship
