---
- name: Unconfigure starship
  include_role:
    name: installer
  vars:
    dotfiles: starship

- name: Uninstall starship from system
  include_role:
    name: installer
  vars:
    package: starship
  when: ansible_distribution != 'Ubuntu'

- name: Uninstall starship from ubuntu
  shell: sh -c 'rm "$(command -v 'starship')"'
  become: true
  when: ansible_distribution == 'Ubuntu'
