# Adopted from technetium ~/.config/hypr/hyprpaper.conf.
splash = false
preload = /home/ryjen/Pictures/wallpaper/manuel-venturini-7vjfkwZ24Ws-unsplash.jpg
wallpaper = , /home/ryjen/Pictures/wallpaper/manuel-venturini-7vjfkwZ24Ws-unsplash.jpg
