# Managed Alacritty base configuration.
# source-of-truth: ryjen/dotfiles

[font]
size = 18

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"
