---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: mcp-ubuntu
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    privileged: true
    command: /sbin/init
    pre_build_image: true
provisioner:
  name: ansible
ansible:
  playbooks:
    converge: converge.yml
    verify: verify.yml
verifier:
  name: ansible
