---
- name: Setup motd
  copy:
    src: files/motd
    dest: /etc/motd
  become: true
  when: install_state == "present"

- name: Remove motd
  file:
    path: /etc/motd
    state: absent
  become: true
  when: install_state == "absent"
