{
  hermes-agent,
  lib,
  pkgs,
  config,
  ...
}:
let
  hermesPackage = hermes-agent.packages.${pkgs.system}.default;

  agentsUpdate = pkgs.writeShellApplication {
    name = "agents-update";
    runtimeInputs = with pkgs; [
      coreutils
      git
      jq
      rsync
    ];
    text = ''
      lock_file="''${1:-$HOME/.agents/.skill-lock.json}"
      cache_dir="''${XDG_CACHE_HOME:-$HOME/.cache}/agent-skills"
      skills_dir="''${AGENTS_SKILLS_DIR:-$HOME/.agents/skills}"

      if [ ! -f "$lock_file" ]; then
        echo "missing lock file: $lock_file" >&2
        exit 1
      fi

      mkdir -p "$cache_dir" "$skills_dir"

      jq -r '.skills | to_entries[] | [.key, .value.sourceUrl, .value.skillPath] | @tsv' "$lock_file" |
        while IFS="$(printf '\t')" read -r name source_url skill_path; do
          if [ -z "$source_url" ] || [ -z "$skill_path" ]; then
            echo "skip $name: missing sourceUrl or skillPath" >&2
            continue
          fi

          repo_hash="$(printf '%s' "$source_url" | sha256sum | cut -d ' ' -f 1)"
          repo_dir="$cache_dir/$repo_hash"

          if [ -d "$repo_dir/.git" ]; then
            git -C "$repo_dir" pull --ff-only
          else
            git clone --depth 1 "$source_url" "$repo_dir"
          fi

          skill_dir="$repo_dir/''${skill_path%/SKILL.md}"
          if [ ! -f "$skill_dir/SKILL.md" ]; then
            echo "skip $name: missing $skill_path in $source_url" >&2
            continue
          fi

          tmp_dir="$skills_dir/.$name.tmp"
          skill_dest="$skills_dir/$name"
          rm -rf "''${tmp_dir:?}"
          mkdir -p "$tmp_dir"
          rsync -a --delete "$skill_dir"/ "$tmp_dir"/
          rm -rf "''${skill_dest:?}"
          mv "$tmp_dir" "$skill_dest"
      echo "updated $name"
        done
    '';
  };
in
{
  options.dotfiles.agents.hermes.enable = lib.mkEnableOption "Hermes agent package and config";

  config = {
    home.packages = [
      agentsUpdate
    ]
    ++ lib.optional config.dotfiles.agents.hermes.enable hermesPackage;

    home.file.".agents/.skill-lock.json".source = ../../files/home/.agents/.skill-lock.json;
    home.file.".hermes/config.yaml" = lib.mkIf config.dotfiles.agents.hermes.enable {
      source = ../../files/home/.hermes/config.yaml;
    };

    xdg.configFile."codex/adopted.d/00-managed.conf".source = ../../files/home/.config/codex/adopted.d/00-managed.conf;
    xdg.configFile."codex/custom.d/.keep".source = ../../files/home/.config/codex/custom.d/.keep;
    xdg.configFile."codex/README.md".source = ../../files/home/.config/codex/README.md;

    home.activation.bootstrapCodexConfig = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
      set -eu

      source_dir="''${XDG_CONFIG_HOME:-$HOME/.config}/codex"
      runtime_dir="$HOME/.codex"
      runtime_file="$runtime_dir/config.toml"

      mkdir -p "$runtime_dir"
      umask 077
      tmp_file="$(mktemp "$runtime_dir/.config.toml.tmp.XXXXXX")"
      trap 'rm -f "$tmp_file"' EXIT

      {
        printf '%s\n' '# Generated by Home Manager from ~/.config/codex layers.'
        printf '%s\n' '# Canonical reconciliation path: configctl init apply codex-config.'
        printf '%s\n' '# Do not edit directly; update ~/.config/codex/local.conf or configctl layers.'
        printf '\n'

        export LC_ALL=C

        for fragment in "$source_dir"/adopted.d/*.conf; do
          [ -e "$fragment" ] || continue
          cat "$fragment"
          printf '\n'
        done

        for fragment in "$source_dir"/custom.d/*.conf; do
          [ -e "$fragment" ] || continue
          cat "$fragment"
          printf '\n'
        done

        if [ -f "$source_dir/local.conf" ]; then
          cat "$source_dir/local.conf"
          printf '\n'
        fi
      } > "$tmp_file"

      chmod u+rw,go-rwx "$tmp_file"
      mv "$tmp_file" "$runtime_file"
      trap - EXIT
    '';

    home.file.".codex/rules/default.rules".source = ../../files/home/.codex/rules/default.rules;
  };
}
