{
  lib,
  ...
}:
{
  imports = [
    ./agents.nix
    ./alacritty.nix
    ./android.nix
    ./bat.nix
    ./bitwarden.nix
    ./browser.nix
    ./byobu.nix
    ./common.nix
    ./configctl.nix
    ./cowsay.nix
    ./devtools.nix
    ./direnv.nix
    ./fortunes.nix
    ./fzf.nix
    ./headroom.nix
    ./helix.nix
    ./git.nix
    ./gpg.nix
    ./grimblast.nix
    ./hypr.nix
    ./idle.nix
    ./input.nix
    ./keyring.nix
    ./lsd.nix
    ./lolcat.nix
    ./micrantha.nix
    ./meeting.nix
    ./mise.nix
    ./music.nix
    ./music-library.nix
    ./neovim.nix
    ./npm.nix
    ./office.nix
    ./opencode.nix
    ./openwork.nix
    ./pass.nix
    ./pinentry.nix
    ./pip.nix
    ./playwright.nix
    ./session.nix
    ./starship.nix
    ./taskwarrior.nix
    ./tmux.nix
    ./unreal.nix
    ./uv.nix
    ./vscode.nix
    ./waybar.nix
    ./zsh.nix
    ./zellij.nix
  ]
  ++ lib.optional (builtins.pathExists ../../secrets.yaml) ./secrets.nix;
}
