#!/usr/bin/env zsh

DIR=${0:a:h}

type pip2 > /dev/null

if [[ $? -eq 0 ]]; then
  cat $DIR/required_py2.txt | xargs pip2 install
else
  echo "'pip2' not installed"
fi

type pip3 > /dev/null

if [[ $? -eq 0 ]]; then
  cat $DIR/required_py3.txt | xargs pip3 install
else
  echo "'pip3' not installed"
fi

