#!/usr/bin/env bash
# Harden pre-commit-installed git hooks against Nix store garbage collection.
#
# `pre-commit install` bakes an absolute /nix/store/... path into each hook.
# After a rebuild the derivation moves (and may be GC'd), so the hook dies with
# a cryptic "No such file or directory". This script keeps the baked-in store
# path as the primary interpreter but falls back to `pre-commit` on PATH when
# that path is gone, and otherwise fails with a clear message.
#
# Idempotent: already-hardened hooks are left untouched.
#
# Usage: harden-pre-commit-hooks.sh [hooks-dir]

set -u

hook_dir="${1:-}"
if [ -z "$hook_dir" ]; then
  hook_dir="$(git rev-parse --path-format=absolute --git-common-dir 2>/dev/null)/hooks"
fi
[ -d "$hook_dir" ] || exit 0

for hook in "$hook_dir"/pre-commit "$hook_dir"/pre-push; do
  [ -f "$hook" ] || continue
  grep -q 'File generated by pre-commit' "$hook" || continue

  sed -i 's@^#!/nix/store/.*@#!/usr/bin/env bash@' "$hook"

  sed -i 's@^exec \(/nix/store/[^ ]*\)/bin/pre-commit@PRE_COMMIT="\1/bin/pre-commit"\n[ -x "$PRE_COMMIT" ] || PRE_COMMIT="$(command -v pre-commit || true)"\n[ -n "$PRE_COMMIT" ] || { echo "ERROR: pre-commit not found (run: nix develop)" >\&2; exit 1; }\nexec "$PRE_COMMIT"@' "$hook"
done
