---
- name: "Ensure node and npm is installed"
  include_role:
    name: installer
  vars:
    system:
      arch: nodejs-lts-jod
    package: nodejs

- block:
    - name: Install continue
      shell: npm i -g @continuedev/cli
      become: true
      when: install_state == "present"

    - name: Uninstall continue
      shell: npm uninstall -g @continuedev/cli
      become: true
      when: install_state == "absent"

