#!/usr/bin/env zsh

DIR=${0:a:h}

type tic > /dev/null

if [[ $? -ne 0 ]]; then
  echo "'tic' command not found"
  exit 1
fi

tic -x $DIR/xterm-256color-italic.terminfo
tic -x $DIR/tmux-256color.terminfo