#!/usr/bin/env sh

export NODEJS_CHECK_SIGNATURES="no"

plugin=$1
shift

if [[ $# -gt 0 ]]; then
  #skip url
  shift
fi

# dont match these versions
version_excludes='stackless|pyston|pypy|miniconda|micropython|jython|ironpython|anaconda|activepython|\-dev|\-rc[-0-9]?|truffleruby|ree|rbx|mruby|maglev|jruby|\-preview[0-9]?'

# get the latest version
version=$(asdf list-all $plugin | egrep -v "${version_excludes}" | tail -1);

# install latest version
asdf install $plugin $version

# install other versions
for v in "$@"; do
  asdf install $plugin $v
done

asdf global $plugin $version $@

