#!/usr/bin/env zsh

plugin=$1

#skip plugin name
shift

if [[ $# -gt 0 ]]; then
  #skip url
  shift
fi

# dont match these versions
version_excludes='stackless|pyston|pypy|miniconda|micropython|jython|ironpython|anaconda|activepython|\-dev|\-rc[-0-9]?'

# get the latest version
version=$(asdf list-all $plugin | egrep -v "${version_excludes}" | tail -1);

# install latest version
asdf install $plugin $version

# install other versions
for v in "$@"; do
  asdf install $plugin $v
done

asdf global $plugin $version $@

