---
- name: "Ensure alacritty is {{ install_state }}"
  include_role:
    name: installer
  vars:
    package: alacritty

- name: "Ensure alacritty config is {{ install_state }}"
  include_role:
    name: installer
  vars:
    dotfiles: alacritty
