name: Nix CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v17

      - name: Configure Cache
        uses: DeterminateSystems/flakehub-cache-action@v1

      - name: Flake Check
        run: nix flake check --no-build

      - name: Build Home Manager Activation
        run: nix build .#homeConfigurations.ryjen@verify.activationPackage

      - name: Build NixOS System
        run: nix build .#nixosConfigurations.verify.config.system.build.toplevel
