{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.ryjen.ai.model-router;
  planoCfg = config.ryjen.ai.plano;
in
{
  options.ryjen.ai.model-router = {
    enable = lib.mkEnableOption "user-level model-router policy/profile configuration";

    profileName = lib.mkOption {
      type = lib.types.str;
      default = "local-first-dev";
    };

    planoBaseUrl = lib.mkOption {
      type = lib.types.str;
      default = "http://${planoCfg.listenerAddress}:${toString planoCfg.listenerPort}";
      description = "Plano gateway URL used by model-router-aware tools.";
    };

    ledgerPath = lib.mkOption {
      type = lib.types.str;
      default = "${config.xdg.stateHome}/model-router/route-decisions.jsonl";
    };
  };

  config = lib.mkIf cfg.enable {
    xdg.configFile."model-router/profiles/${cfg.profileName}.yaml".text = ''
      # Generated by Home Manager.
      #
      # User-level model-router policy profile for Dubnium/Plano client ergonomics.
      # This is not a Plano runtime config and does not start services.

      profile: ${cfg.profileName}
      version: 0.1.0

      runtime:
        gateway: plano
        plano_base_url: ${cfg.planoBaseUrl}
        openai_base_url: ${cfg.planoBaseUrl}/v1
        plano_config_file: ${config.xdg.configHome}/${planoCfg.configFile}

      principles:
        - fail closed on privacy uncertainty
        - prefer local execution for private code and unpublished docs
        - preserve affinity within agentic execution loops
        - allow fallback only for operational failures
        - record routing decisions for later Anthesis evidence

      privacy_classes:
        local_only:
          description: Secrets, private source code, unpublished documents, and sensitive personal data
          allowed_boundaries:
            - local
        trusted_cloud_ok:
          description: Work content allowed for explicitly approved cloud providers
          allowed_boundaries:
            - local
            - trusted_cloud
        public_cloud_ok:
          description: Public-safe content
          allowed_boundaries:
            - local
            - trusted_cloud
            - public_cloud

      sources:
        - id: dubnium-local-code
          provider: plano
          plano_alias: local-code
          privacy_boundary: local
          cost_class: free
          capabilities:
            - code
            - summarize
            - rewrite
            - classify
          context_tokens: 32768
        - id: dubnium-fast-local
          provider: plano
          plano_alias: fast-local
          privacy_boundary: local
          cost_class: free
          capabilities:
            - summarize
            - rewrite
            - classify
          context_tokens: 32768

      rules:
        - id: private-code-local-only
          description: Private code and unpublished docs must stay on local routing surfaces
          when:
            data_class:
              - source_code
              - secrets
              - unpublished_docs
              - sensitive_personal_data
          effect: require_local
        - id: public-cheap-work-prefer-free
          description: Public summarize/rewrite/classify tasks should prefer free/local routes
          when:
            privacy_class:
              - public_cloud_ok
            task:
              - summarize
              - rewrite
              - classify
          effect: prefer
          parameters:
            cost_class:
              - free
              - low

      fallback:
        allowed_reasons:
          - timeout
          - rate_limited
          - provider_5xx
          - transient_network_failure
          - invalid_structured_output_after_retry
        forbidden_reasons:
          - privacy_violation
          - forbidden_provider
          - budget_hard_limit
          - safety_policy_denial
          - missing_approval_gate

      affinity:
        enabled: true
        key_sources:
          - anthesis_execution_id
          - session_id
          - explicit_affinity_key

      ledger:
        format: jsonl
        path: ${cfg.ledgerPath}
    '';

    home.sessionVariables = {
      MODEL_ROUTER_PROFILE = cfg.profileName;
      MODEL_ROUTER_CONFIG_HOME = "${config.xdg.configHome}/model-router";
      MODEL_ROUTER_STATE_HOME = "${config.xdg.stateHome}/model-router";
      MODEL_ROUTER_LEDGER = cfg.ledgerPath;
      PLANO_BASE_URL = cfg.planoBaseUrl;
      OPENAI_BASE_URL = "${cfg.planoBaseUrl}/v1";
    };

    home.file.".local/bin/model-router-env" = {
      executable = true;
      text = ''
        #!/usr/bin/env bash
        set -euo pipefail

        export MODEL_ROUTER_PROFILE="''${MODEL_ROUTER_PROFILE:-${cfg.profileName}}"
        export MODEL_ROUTER_CONFIG_HOME="''${MODEL_ROUTER_CONFIG_HOME:-''${XDG_CONFIG_HOME:-$HOME/.config}/model-router}"
        export MODEL_ROUTER_STATE_HOME="''${MODEL_ROUTER_STATE_HOME:-''${XDG_STATE_HOME:-$HOME/.local/state}/model-router}"
        export MODEL_ROUTER_LEDGER="''${MODEL_ROUTER_LEDGER:-${cfg.ledgerPath}}"
        export PLANO_BASE_URL="''${PLANO_BASE_URL:-${cfg.planoBaseUrl}}"
        export OPENAI_BASE_URL="''${OPENAI_BASE_URL:-${cfg.planoBaseUrl}/v1}"

        if [ "$#" -eq 0 ]; then
          env | grep -E '^(MODEL_ROUTER|PLANO|OPENAI_BASE_URL)=' | sort
        else
          exec "$@"
        fi
      '';
    };
  };
}
